name: simple_repair
description: 小汽修店管理系统
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  image_picker: ^1.0.7
  share_plus: ^7.2.1
  file_picker: ^6.1.1

flutter:
  uses-material-design: true
